apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mqtt-blackbox-exporter.fullname" . }}
  labels:
    release: prom
spec:
  endpoints:
  - path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "mqtt-blackbox-exporter.labels" . | nindent 6 }}
      